import { useState } from 'react';
import { CheckCircle2, ChevronDown, Mail, Menu, MessageCircle, Send } from 'lucide-react';
import ClientSidebar from '../components/sidebars/ClientSidebar';

type Props = { username: string };
const faqs = [
  ['How do I book an appointment?', 'Open Book Service from the sidebar or header, select a service, barber, date, and available time, then submit your request.'],
  ['Can I change my appointment?', 'Yes. Contact the team as soon as possible with your booking reference so we can help with rescheduling.'],
  ['Where can I see my transactions?', 'Your complete payment and booking records are available under Transactions in the member space.'],
  ['How do I choose a haircut?', 'Browse the Lookbook for curated Pinterest inspiration, then mention your preferred style in your booking notes.'],
];

export default function ClientSupport({ username }: Props) {
  const [open, setOpen] = useState(false);
  const [expanded, setExpanded] = useState<number | null>(0);
  const [sent, setSent] = useState(false);
  const name = username.trim() || 'Member';
  return (
    <main className="min-h-screen bg-[#f7f7f7] font-sans text-zinc-950 selection:bg-[#c7a65e] selection:text-white">
      <div className="fixed inset-y-0 left-0 z-40 hidden lg:block"><ClientSidebar username={username} active="support" onNavigate={(route) => { window.location.hash = route; }} onClose={() => setOpen(false)} /></div>
      {open && <div className="fixed inset-0 z-50 lg:hidden" role="dialog" aria-modal="true"><button type="button" className="absolute inset-0 bg-zinc-950/25 backdrop-blur-[2px]" onClick={() => setOpen(false)} aria-label="Close navigation" /><div className="relative h-full w-72"><ClientSidebar username={username} active="support" onNavigate={(route) => { window.location.hash = route; }} onClose={() => setOpen(false)} /></div></div>}
      <div className="min-h-screen lg:ml-72">
        <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-zinc-200/70 bg-white/85 px-3.5 backdrop-blur-lg sm:h-20 sm:px-8 lg:px-12"><div className="flex items-center gap-3"><button type="button" onClick={() => setOpen(true)} className="flex h-10 w-10 items-center justify-center rounded-2xl border border-zinc-200/80 bg-zinc-50/80 lg:hidden" aria-label="Open navigation"><Menu size={18} /></button><div className="hidden h-6 w-0.5 rounded-full bg-[#c7a65e]/40 sm:block" /><div><p className="text-[8px] font-black tracking-[.28em] text-[#c7a65e] uppercase sm:text-[9px]">Portal</p><p className="text-xs font-black uppercase tracking-tighter sm:text-base">Member <span className="font-light text-zinc-400">space</span></p></div></div><div className="flex h-9 w-9 items-center justify-center rounded-full bg-zinc-950 text-xs font-black text-[#c7a65e]">{name[0].toUpperCase()}</div></header>
        <div className="mx-auto max-w-300 px-3.5 py-8 sm:px-8 sm:py-12 lg:px-12"><div className="mb-9"><div className="inline-flex items-center gap-2 rounded-full border border-[#e7dcc5] bg-[#f9f5ea] px-3 py-1.5 text-[9px] font-black tracking-[.24em] text-[#bb9143] uppercase"><MessageCircle size={12} /> Member care</div><h1 className="mt-4 text-4xl font-black uppercase leading-[.9] tracking-[-.08em] sm:text-6xl">How can we <span className="italic text-zinc-500">help?</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-zinc-500">Questions about your appointment, membership, or visit? Our team is here to keep your experience sharp and simple.</p></div>
          <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><section className="rounded-[1.75rem] bg-zinc-950 p-6 text-white shadow-[0_16px_35px_rgba(18,18,18,.12)] sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#c7a65e]">Direct support</p><h2 className="mt-3 text-3xl font-black uppercase leading-none tracking-[-.07em]">Talk to the <span className="italic text-zinc-400">team.</span></h2><p className="mt-4 text-sm leading-6 text-zinc-400">Send us a note and our barbershop team will get back to you with the right answer.</p><div className="mt-7 flex items-center gap-3 border-t border-white/10 pt-5"><div className="rounded-xl bg-[#c7a65e]/15 p-3 text-[#c7a65e]"><Mail size={18} /></div><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-zinc-500">Email us</p><p className="text-sm font-bold">hello@hustlefriends.co</p></div></div></section>
            <form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="rounded-[1.75rem] border border-zinc-200 bg-white p-6 shadow-sm sm:p-8">{sent ? <div className="flex h-full min-h-56 flex-col items-center justify-center text-center"><CheckCircle2 className="text-emerald-500" size={42} /><h2 className="mt-4 text-xl font-black uppercase">Message received</h2><p className="mt-2 text-sm text-zinc-500">Thanks, {name}. We will be in touch shortly.</p><button type="button" onClick={() => setSent(false)} className="mt-5 text-[10px] font-black uppercase tracking-[.15em] text-[#a37d2d]">Send another message</button></div> : <><h2 className="text-lg font-black uppercase tracking-[-.04em]">Send a message</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><input required placeholder="Your name" defaultValue={name} className="rounded-xl border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm outline-none transition focus:border-[#c7a65e] sm:col-span-1" /><input required type="email" placeholder="Email address" className="rounded-xl border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm outline-none transition focus:border-[#c7a65e]" /></div><textarea required placeholder="How can we help?" rows={4} className="mt-3 w-full resize-none rounded-xl border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm outline-none transition focus:border-[#c7a65e]" /><button className="mt-4 inline-flex items-center gap-2 rounded-full bg-zinc-950 px-5 py-3 text-[10px] font-black uppercase tracking-[.16em] text-white transition hover:bg-[#c7a65e] hover:text-zinc-950">Send message <Send size={14} /></button></>}</form></div>
          <section className="mt-10"><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#bb9143]">Frequently asked</p><div className="mt-4 overflow-hidden rounded-3xl border border-zinc-200 bg-white">{faqs.map(([question, answer], index) => <div key={question} className="border-b border-zinc-100 last:border-0"><button type="button" onClick={() => setExpanded(expanded === index ? null : index)} className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left text-sm font-black uppercase tracking-[-.02em] transition hover:bg-zinc-50 sm:px-7"><span>{question}</span><ChevronDown size={17} className={`shrink-0 text-[#c7a65e] transition ${expanded === index ? 'rotate-180' : ''}`} /></button>{expanded === index && <p className="px-5 pb-5 text-sm leading-6 text-zinc-500 sm:px-7">{answer}</p>}</div>)}</div></section>
          <footer className="mt-14 border-t border-zinc-200 pt-5 text-[9px] font-black uppercase tracking-[.2em] text-zinc-400">Hustle Friends Co. ® 2026 <span className="mx-2 text-[#c7a65e]">•</span> Work Hard • Stay Sharp</footer>
        </div>
      </div>
    </main>
  );
}
