import { Banknote, Bell, ChevronRight, Menu, Minus, Plus, Search, ShoppingBag, Trash2, UserRound } from 'lucide-react';
import { useMemo, useState } from 'react';
import StaffSidebar from '../components/sidebars/StaffSidebar';

type Product = { id: string; name: string; detail: string; price: number };
const products: Product[] = [
  { id: 'pomade', name: 'Hustle Pomade', detail: '100ml / Grooming', price: 450 },
  { id: 'clay', name: 'Matte Clay', detail: '100ml / Grooming', price: 520 },
  { id: 'oil', name: 'Beard Oil', detail: '30ml / Care', price: 380 },
  { id: 'wash', name: 'Daily Shampoo', detail: '250ml / Care', price: 620 },
];

export default function StaffPos() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [notice, setNotice] = useState('');
  const [cart, setCart] = useState<Record<string, number>>({});
  const [query, setQuery] = useState('');
  const showNotice = (message: string) => { setNotice(message); setSidebarOpen(false); window.setTimeout(() => setNotice(''), 3000); };
  const visibleProducts = products.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()));
  const cartItems = products.filter((product) => cart[product.id]);
  const total = useMemo(() => cartItems.reduce((sum, product) => sum + product.price * cart[product.id], 0), [cartItems, cart]);
  const add = (id: string) => setCart((items) => ({ ...items, [id]: (items[id] || 0) + 1 }));
  const remove = (id: string) => setCart((items) => { const next = { ...items }; if (next[id] <= 1) delete next[id]; else next[id] -= 1; return next; });

  return (
    <main className="min-h-screen w-full bg-[#f7f7f7] font-sans text-zinc-950">
      <div className="fixed inset-y-0 left-0 z-40 hidden lg:block"><StaffSidebar onClose={() => setSidebarOpen(false)} onNotice={showNotice} /></div>
      {sidebarOpen && <div className="fixed inset-0 z-50 lg:hidden" role="dialog" aria-modal="true"><button type="button" className="absolute inset-0 bg-zinc-950/25 backdrop-blur-[2px]" onClick={() => setSidebarOpen(false)} aria-label="Close navigation" /><div className="relative h-full w-72"><StaffSidebar onClose={() => setSidebarOpen(false)} onNotice={showNotice} /></div></div>}
      <div className="min-h-screen lg:ml-72">
        <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-zinc-200/70 bg-white/85 px-3.5 backdrop-blur-lg sm:h-20 sm:px-8 lg:px-12"><div className="flex items-center gap-3"><button type="button" onClick={() => setSidebarOpen(true)} className="flex h-10 w-10 items-center justify-center rounded-2xl border border-zinc-200/80 bg-zinc-50 text-zinc-800 lg:hidden" aria-label="Open navigation"><Menu size={18} /></button><div className="border-l-2 border-[#c7a65e]/60 pl-3"><p className="text-[9px] font-black tracking-[0.28em] text-[#bb9143] uppercase">Portal</p><p className="text-sm font-black uppercase sm:text-base">Staff <span className="font-light text-zinc-400">terminal</span></p></div></div><div className="flex items-center gap-3"><button type="button" onClick={() => showNotice('You are all caught up.')} className="rounded-2xl border border-zinc-200/80 bg-zinc-50 p-2.5 text-zinc-700" aria-label="Notifications"><Bell size={16} /></button><div className="flex h-9 w-9 items-center justify-center rounded-full bg-zinc-950 text-xs font-black text-[#c7a65e]"><UserRound size={15} /></div></div></header>
        <div className="mx-auto max-w-[1570px] px-3.5 py-4 sm:px-6 sm:py-8 lg:px-10 xl:px-12">{notice && <p className="mb-5 rounded-xl border border-[#dfcfaa] bg-[#fdf9ef] px-4 py-3 text-xs font-medium text-[#735719]" role="status">{notice}</p>}<div className="inline-flex items-center gap-1.5 rounded-full border border-[#e7dcc5] bg-[#f9f5ea] px-2.5 py-1 text-[9px] font-black tracking-[0.24em] text-[#bb9143] uppercase"><span className="h-1.5 w-1.5 rounded-full bg-[#c7a65e]" />Internal access only</div><div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-black tracking-[-0.07em] uppercase sm:text-6xl">Walk-in <span className="text-zinc-500 italic">payment.</span></h1><p className="mt-3 text-sm text-zinc-500">Process a walk-in sale with server-verified totals.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-2 text-[9px] font-black tracking-widest text-emerald-700 uppercase"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Terminal online</div></div>
          <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_380px]"><section className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black">Retail products</h2><p className="mt-1 text-xs text-zinc-500">Select an item to add it to the ticket.</p></div><label className="flex items-center gap-2 rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-zinc-500"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-xs outline-none sm:w-48" placeholder="Search products" aria-label="Search products" /></label></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{visibleProducts.map((product) => <button type="button" key={product.id} onClick={() => add(product.id)} className="group rounded-xl border border-zinc-200 bg-zinc-50 p-4 text-left transition hover:border-[#c7a65e]"><div className="flex h-24 items-center justify-center rounded-lg bg-white text-[#b08b3a]"><ShoppingBag size={30} strokeWidth={1.2} /></div><div className="mt-4 flex items-end justify-between"><div><p className="text-sm font-bold">{product.name}</p><p className="mt-1 text-[10px] text-zinc-500">{product.detail}</p></div><p className="text-sm font-black text-[#a37d2d]">₱{product.price}</p></div><p className="mt-3 text-[9px] font-black tracking-widest text-zinc-500 uppercase group-hover:text-[#a37d2d]">Add to ticket +</p></button>)}</div></section>
          <aside className="flex h-fit flex-col rounded-2xl border border-[#dfcfaa] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between border-b border-zinc-100 pb-5"><div><p className="text-[9px] font-black tracking-[0.2em] text-[#a37d2d] uppercase">Current ticket</p><h2 className="mt-1 text-xl font-black">Walk-in sale</h2></div><Banknote className="text-[#b08b3a]" /></div><div className="min-h-48 flex-1 py-4">{cartItems.length === 0 ? <div className="flex h-40 flex-col items-center justify-center text-center text-zinc-400"><ShoppingBag size={25} /><p className="mt-3 text-xs">Your ticket is empty</p></div> : cartItems.map((product) => <div key={product.id} className="mb-4 flex items-center justify-between gap-2"><div><p className="text-xs font-bold">{product.name}</p><p className="mt-1 text-[10px] text-zinc-500">₱{product.price} each</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => remove(product.id)} className="rounded-md border border-zinc-200 p-1 text-zinc-500" aria-label={`Remove ${product.name}`}><Minus size={12} /></button><span className="w-4 text-center text-xs">{cart[product.id]}</span><button type="button" onClick={() => add(product.id)} className="rounded-md border border-zinc-200 p-1 text-zinc-500" aria-label={`Add ${product.name}`}><Plus size={12} /></button><button type="button" onClick={() => setCart((items) => { const next = { ...items }; delete next[product.id]; return next; })} className="ml-1 text-zinc-400 hover:text-red-500" aria-label={`Delete ${product.name}`}><Trash2 size={14} /></button></div></div>)}</div><div className="border-t border-zinc-100 pt-5"><div className="flex items-center justify-between text-xs text-zinc-500"><span>Subtotal</span><span>₱{total.toLocaleString()}</span></div><div className="mt-3 flex items-center justify-between"><span className="text-sm font-bold">Total due</span><span className="text-2xl font-black text-[#a37d2d]">₱{total.toLocaleString()}</span></div><button type="button" disabled={!total} onClick={() => showNotice('Checkout will connect to the POS API when enabled.')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-zinc-950 py-3.5 text-[10px] font-black tracking-[0.17em] text-white uppercase transition hover:bg-[#c7a65e] hover:text-zinc-950 disabled:cursor-not-allowed disabled:opacity-30">Charge customer <ChevronRight size={15} /></button></div></aside></div>
        </div>
      </div>
    </main>
  );
}
